title: Code
baseurl: ""
url: "http://code.slipthrough.net"
twitter_username: gb_r
github_username:  garyb
respository: garyb/slipthrough-code
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
